export const products = [
    {
        id: "kadsnk",
        title: "Auriculares",
        subtitle: "Auriculares inhalambricos 7.1",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        price: 14500,
        stock: 10,
        category: "auriculares",
        img: "https://redragon.es/content/uploads/2021/09/ZEUS-X.png",
    },
    {
        id: "kujasbd",
        title: "Deimos k599",
        subtitle: "Teclado mecanico inhalambrico ",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        price: 12500,
        stock: 15,
        category: "teclado",
        img: "https://redragon.es/content/uploads/2021/12/DEIMOS.png",
    },
    {
        id: "kaldsmad",
        title: "Storm pro",
        subtitle: "Mouse de juego inalámbrico recargable",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        price: 7200,
        stock: 25,
        category: "ratones",
        img: "https://redragon.es/content/uploads/2022/05/storm-pro-png.png",
    },
    {
        id: "oibvoiv",
        title: "Hitman",
        subtitle: "Camara web full hd",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        price: 8500,
        stock: 12,
        category: "camaras",
        img: "https://redragon.es/content/uploads/2021/05/HITMAN-800.png",
    },
    {
        id: "oilkns",
        title: "Ruby",
        subtitle: 'Monitor 27" 144hz',
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        price: 50000,
        stock: 7,
        category: "perifericos",
        img: "https://redragon.es/content/uploads/2022/02/ruby-producto.png",
    },
];
