export const products = [
    {
        id: "kadsnk",
        title: "Auriculares",
        description: "Estos son auris de puta madre",
        price: 14500,
        stock: 10,
        category: "auriculares",
        img: "https://redragon.es/content/uploads/2021/09/ZEUS-X.png",
    },
    {
        id: "kujasbd",
        title: "Deimos k599",
        description: "Este es un teclado de puta madre",
        price: 12500,
        stock: 15,
        category: "teclado",
        img: "https://redragon.es/content/uploads/2021/12/DEIMOS.png",
    },
    {
        id: "kaldsmad",
        title: "Storm pro",
        description: "Este es un mouse de puta madre",
        price: 7200,
        stock: 25,
        category: "ratones",
        img: "https://redragon.es/content/uploads/2022/05/storm-pro-png.png",
    },
    {
        id: "oibvoiv",
        title: "Hitman",
        description: "Camara web full hd",
        price: 8500,
        stock: 12,
        category: "camaras",
        img: "https://redragon.es/content/uploads/2021/05/HITMAN-800.png",
    },
    {
        id: " oilkns",
        title: "Ruby",
        description: "Este es un monitor de puta madre",
        price: 50000,
        stock: 7,
        category: "perifericos",
        img: "https://redragon.es/content/uploads/2022/02/ruby-producto.png",
    },
];
